Repository sritikamanjrekar/Print-Hacktoberfest2023, pull requests merged in 2022-10, with the labels that each got.

#26 Revert "Add Ruby"
  Ruby/nikodyring.rb
Labels: hacktoberfest-accepted

#25 Create bubble_sort.cpp
  C++/bubble_sort.cpp
Labels: invalid

#30 hello in Go language
  Go/Hello.go
Labels: hacktoberfest, hacktoberfest-accepted

#29 hello in solidity
  solidity/hello.sol
Labels: hacktoberfest, hacktoberfest-accepted

#31 print name in dart
  dart/print-name.dart
Labels: hacktoberfest, hacktoberfest-accepted

#32 Create PrintName.cpp
  C++/PrintName.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#33 printing in JS
  javascript/dsnoeijer.js
Labels: hacktoberfest, hacktoberfest-accepted

#39 Create display-name.dart
  dart/display-name.dart
Labels: hacktoberfest, hacktoberfest-accepted

#41 Create name_print.cpp
  C++/name_print.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#42 Print-Hacktoberfest2022 in Ruby
  Ruby/hello.rb
Labels: hacktoberfest, hacktoberfest-accepted

#43 adding name
  Java/my_name.java
Labels: hacktoberfest, hacktoberfest-accepted

#46 print using kotlin
  Kotlin/print_in_kotlin.kt
Labels: hacktoberfest, hacktoberfest-accepted

#47 namePrint.cpp
  C++/namePrint.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#50 Print_name.cpp
  Print_name.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#51 Printing Hacktoberfest2022 in ruby has been added
  C++/namePrintNew.cpp
  C++/namePrintNew.exe
  Ruby/PrintHacktoberfest2022.rb
Labels: hacktoberfest, hacktoberfest-accepted

#52 Added
  C++/Nam_Print.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#53 Create print
  Python/Print_my_name.py
Labels: hacktoberfest, hacktoberfest-accepted

#57 Create Helloname.sol
  solidity/Helloname.sol
Labels: hacktoberfest, hacktoberfest-accepted

#58 Created name-print.cpp in c++
  C++/name-print.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#62 Updated with my name in Solidity.md
  solidity/john.sol
Labels: hacktoberfest, hacktoberfest-accepted

#65 Create Name_Vijay.cpp
  C++/Name_Vijay.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#63 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#66 my intro
  Python/Intro.py
Labels: hacktoberfest, hacktoberfest-accepted

#68 Create my_name.py
  Python/my_name.py
Labels: hacktoberfest, hacktoberfest-accepted

#69 added my name in java
  C++/namePrint.cpp
  Java/Print_Ashlin.java
Labels: hacktoberfest, hacktoberfest-accepted

#70 Name_Vinay.cpp
  C++/Name_Vinay.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#71 Create print_name
  Java/print_name.java
Labels: hacktoberfest, hacktoberfest-accepted

#72 Name_Sharyu added
  C++/Name_Sharyu.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#74 added Name in cpp
  C++/Print__Name.cpp
  C++/Print__Name.exe
Labels: hacktoberfest, hacktoberfest-accepted

#76 Adding Name using Java by Yash Mittal
  Java/myname.java
Labels: hacktoberfest, hacktoberfest-accepted

#79 Ruby Hello from bhutan
  Ruby/lalit.rb
Labels: hacktoberfest, hacktoberfest-accepted

#87 Print my name in Python
  Python/Print_my_name.py
Labels: hacktoberfest, hacktoberfest-accepted

#90 Create my_name.cpp
  C++/my_name.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#92 Print_Aditya.java
  Java/Print_Aditya.java
Labels: hacktoberfest, hacktoberfest-accepted

#93 print_myname.java
  Java/print_myname.java
Labels: hacktoberfest, hacktoberfest-accepted

#96 Added name in anu.java
  Java/anu.java
Labels: hacktoberfest, hacktoberfest-accepted

#99 Added name
  C++/Printname (2).cpp
  C/printmyname.c
Labels: hacktoberfest, hacktoberfest-accepted

#102 added my_print.cpp
  C++/my_print.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#103 Added the code for required task.
  Issue34.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#104 EUCLID ALGO
  EUCLID.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#105 Create printname.c
  C/printname.c
Labels: hacktoberfest, hacktoberfest-accepted

#94 Create my name.java
  my name.java
Labels: invalid

#97 Create shubham.java
  Java/shubham.java
Labels: invalid

#109 Create Madhur.cpp
  C++/Madhur.cpp
Labels: hacktoberfest, hacktoberfest-accepted
